# name: Build Check

# on:
#   push:
#     branches: ["main"]
#     paths:
#       - "**.py"
#       - "Dockerfile"
#       - "uv.lock"
#       - "pyproject.toml"
#   pull_request:
#     branches: ["main"]

# jobs:
#   docker-verify:
#     name: Verify Docker Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: Dockerfile
#           push: false
#           tags: aether:ci-test
#           cache-from: type=gha
#           chat-to: type=gha, mode=max
