# name: Link Check

# on:
#   push:
#     branches: ["main"]
#     paths:
#       - "**.py"
#       - "pyproject.toml"
#       - "uv.lock"
#   pull_request:
#     branches: ["main"]
#     paths:
#       - "**.py"
#       - "pyproject.toml"
#       - "uv.lock"

# jobs:
#   black-check:
#     name: Check Formatting (black)
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Set up Python 3.12
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"
#       - name: Install uv
#         run: curl -LsSf https://astral.sh/uv/install.sh | sh
#       - name: Install dependencies
#         run: uv sync --dev
#       - name: Run Black Check
#         run: uv run black --check .
        